{"name": "Find pet by the 'Sold' status", "status": "broken", "statusDetails": {"message": "pydantic_core._pydantic_core.ValidationError: 1 validation error for Pet\n  Input should be a valid dictionary or instance of Pet [type=model_type, input_value=[{'id': 777, 'category': ...: [], 'status': 'sold'}], input_type=list]\n    For further information visit https://errors.pydantic.dev/2.5/v/model_type", "trace": "self = <test_api.TestApi object at 0x000002A19D874B10>, api_client = <utils.api_client.ApiClient object at 0x000002A19C89AD10>\n\n    @allure.title(\"Find pet by the 'Sold' status\")\n    def test_find_pet_200(self, api_client):\n        params = {\n            \"status\": \"sold\"\n        }\n        response = api_client.get(\"/pet/findByStatus\", params)\n        print(response)\n        with allure.step(f\"Check status {response.status_code}\"):\n            assert response.status_code == 200\n        if response.ok:\n            response_object = response.json()\n            with allure.step(\"Validate response\"):\n>               assert api_client.validate_response(response_object, Pet)\n\ntests\\test_api.py:174: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <utils.api_client.ApiClient object at 0x000002A19C89AD10>\nresult = [{'category': {'id': 888, 'name': 'This is my new category'}, 'id': 777, 'name': 'This is my new pet', 'status': 'sold...', 'photoUrls': ['string'], ...}, {'category': {'id': 1, 'name': 'cat'}, 'id': 1, 'name': 'dog', 'photoUrls': [], ...}]\nmodel = <class 'models.pet.Pet'>\n\n    @allure.step(\"Validate response data\")\n    def validate_response(self, result: object, model: BaseModel):\n>       return model.model_validate(result)\nE       pydantic_core._pydantic_core.ValidationError: 1 validation error for Pet\nE         Input should be a valid dictionary or instance of Pet [type=model_type, input_value=[{'id': 777, 'category': ...: [], 'status': 'sold'}], input_type=list]\nE           For further information visit https://errors.pydantic.dev/2.5/v/model_type\n\nutils\\api_client.py:46: ValidationError"}, "steps": [{"name": "Get request to '/pet/findByStatus'", "status": "passed", "parameters": [{"name": "path", "value": "'/pet/findByStatus'"}, {"name": "params", "value": "{'status': 'sold'}"}], "start": 1704715252146, "stop": 1704715252904}, {"name": "Check status 200", "status": "passed", "start": 1704715252904, "stop": 1704715252904}, {"name": "Validate response", "status": "broken", "statusDetails": {"message": "pydantic_core._pydantic_core.ValidationError: 1 validation error for Pet\n  Input should be a valid dictionary or instance of Pet [type=model_type, input_value=[{'id': 777, 'category': ...: [], 'status': 'sold'}], input_type=list]\n    For further information visit https://errors.pydantic.dev/2.5/v/model_type\n", "trace": "  File \"D:\\Pycharm_Projects\\api-testing-exam\\tests\\test_api.py\", line 174, in test_find_pet_200\n    assert api_client.validate_response(response_object, Pet)\n  File \"D:\\Pycharm_Projects\\api-testing-exam\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"D:\\Pycharm_Projects\\api-testing-exam\\utils\\api_client.py\", line 46, in validate_response\n    return model.model_validate(result)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Pycharm_Projects\\api-testing-exam\\.venv\\Lib\\site-packages\\pydantic\\main.py\", line 503, in model_validate\n    return cls.__pydantic_validator__.validate_python(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "steps": [{"name": "Validate response data", "status": "broken", "statusDetails": {"message": "pydantic_core._pydantic_core.ValidationError: 1 validation error for Pet\n  Input should be a valid dictionary or instance of Pet [type=model_type, input_value=[{'id': 777, 'category': ...: [], 'status': 'sold'}], input_type=list]\n    For further information visit https://errors.pydantic.dev/2.5/v/model_type\n", "trace": "  File \"D:\\Pycharm_Projects\\api-testing-exam\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"D:\\Pycharm_Projects\\api-testing-exam\\utils\\api_client.py\", line 46, in validate_response\n    return model.model_validate(result)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Pycharm_Projects\\api-testing-exam\\.venv\\Lib\\site-packages\\pydantic\\main.py\", line 503, in model_validate\n    return cls.__pydantic_validator__.validate_python(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "parameters": [{"name": "result", "value": "[{'id': 777, 'category': {'id': 888, 'name': 'This is my new category'}, 'name': 'This is my new pet', 'tags': [], 'status': 'sold'}, {'id': 1722, 'category': {'id': 1722, 'name': 'dog'}, 'name': 'Dina', 'photoUrls': ['string'], 'tags': [{'id': 1722, 'name': 'female'}], 'status': 'sold'}, {'id': 1, 'category': {'id': 1, 'name': 'cat'}, 'name': 'dog', 'photoUrls': [], 'tags': [], 'status': 'sold'}]"}, {"name": "model", "value": "<class 'models.pet.Pet'>"}], "start": 1704715252904, "stop": 1704715252905}], "start": 1704715252904, "stop": 1704715252907}], "attachments": [{"name": "stdout", "source": "6e711bab-7a6e-41ff-9a25-3121a0adb83b-attachment.txt", "type": "text/plain"}], "start": 1704715252145, "stop": 1704715252907, "uuid": "50fea7ab-4af3-4f17-9f6a-2af9eac56211", "historyId": "d3c570e42e25cff890ef4e13c645562a", "testCaseId": "d3c570e42e25cff890ef4e13c645562a", "fullName": "tests.test_api.TestApi#test_find_pet_200", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api"}, {"name": "subSuite", "value": "TestApi"}, {"name": "host", "value": "DESKTOP-CPFF6BR"}, {"name": "thread", "value": "16376-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api"}]}