{"name": "Change data of a pet with invalid id", "status": "failed", "statusDetails": {"message": "AssertionError: assert 405 == 400\n +  where 405 = <Response [405]>.status_code", "trace": "self = <test_api.TestApi object at 0x000002A19D874D90>, api_client = <utils.api_client.ApiClient object at 0x000002A19C89AD10>\n\n    @allure.title(\"Change data of a pet with invalid id\")\n    def test_update_pet_with_invalid_id_400(self, api_client):\n        pet = {\n            \"id\": \"p\",\n            \"category\": {\n                \"id\": 9,\n                \"name\": \"category9\"\n            },\n            \"name\": \"doggie9\",\n            \"photoUrls\": [\n                \"https://example.com/pet99_photo.jpg\"\n            ],\n            \"tags\": [\n                {\n                    \"id\": 9,\n                    \"name\": \"tag9\"\n                }\n            ],\n            \"status\": \"available\"\n        }\n        response = api_client.put(\"/pet/p\", pet)\n        print(response)\n        with allure.step(f\"Check status {response.status_code}\"):\n>           assert response.status_code == 400\nE           assert 405 == 400\nE            +  where 405 = <Response [405]>.status_code\n\ntests\\test_api.py:158: AssertionError"}, "steps": [{"name": "Put request to '/pet/p'", "status": "passed", "parameters": [{"name": "path", "value": "'/pet/p'"}, {"name": "data", "value": "{'id': 'p', 'category': {'id': 9, 'name': 'category9'}, 'name': 'doggie9', 'photoUrls': ['https://example.com/pet99_photo.jpg'], 'tags': [{'id': 9, 'name': 'tag9'}], 'status': 'available'}"}], "start": 1704715251368, "stop": 1704715252139}, {"name": "Check status 405", "status": "failed", "statusDetails": {"message": "AssertionError: assert 405 == 400\n +  where 405 = <Response [405]>.status_code\n", "trace": "  File \"D:\\Pycharm_Projects\\api-testing-exam\\tests\\test_api.py\", line 158, in test_update_pet_with_invalid_id_400\n    assert response.status_code == 400\n"}, "start": 1704715252140, "stop": 1704715252140}], "attachments": [{"name": "stdout", "source": "3b273ea8-628e-4dd6-bc58-65d089f3c5b9-attachment.txt", "type": "text/plain"}], "start": 1704715251368, "stop": 1704715252140, "uuid": "42ff74c2-cdc4-4471-a3fa-dee9869fb2cb", "historyId": "bdcce4e612080fe2843d0f344438e392", "testCaseId": "bdcce4e612080fe2843d0f344438e392", "fullName": "tests.test_api.TestApi#test_update_pet_with_invalid_id_400", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api"}, {"name": "subSuite", "value": "TestApi"}, {"name": "host", "value": "DESKTOP-CPFF6BR"}, {"name": "thread", "value": "16376-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api"}]}