{"name": "Find pet by the 'Sold' status", "status": "broken", "statusDetails": {"message": "pydantic_core._pydantic_core.ValidationError: 1 validation error for Pet\nphotoUrls\n  Field required [type=missing, input_value={'id': 777, 'category': {...': [], 'status': 'sold'}, input_type=dict]\n    For further information visit https://errors.pydantic.dev/2.5/v/missing", "trace": "self = <test_api.TestApi object at 0x0000021E4E744690>, api_client = <utils.api_client.ApiClient object at 0x0000021E4D6A9050>\n\n    @allure.title(\"Find pet by the 'Sold' status\")\n    def test_find_pet_200(self, api_client):\n        params = {\n            \"status\": \"sold\"\n        }\n        response = api_client.get(\"/pet/findByStatus\", params)\n        print(response)\n        with allure.step(f\"Check status {response.status_code}\"):\n            assert response.status_code == 200\n        if response.ok:\n            response_object = response.json()\n            for pet in response_object:\n                with allure.step(\"Validate pet in response\"):\n>                   assert api_client.validate_response(pet, Pet)\n\ntests\\test_api.py:174: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <utils.api_client.ApiClient object at 0x0000021E4D6A9050>\nresult = {'category': {'id': 888, 'name': 'This is my new category'}, 'id': 777, 'name': 'This is my new pet', 'status': 'sold', ...}, model = <class 'models.pet.Pet'>\n\n    @allure.step(\"Validate response data\")\n    def validate_response(self, result: object, model: BaseModel):\n>       return model.model_validate(result)\nE       pydantic_core._pydantic_core.ValidationError: 1 validation error for Pet\nE       photoUrls\nE         Field required [type=missing, input_value={'id': 777, 'category': {...': [], 'status': 'sold'}, input_type=dict]\nE           For further information visit https://errors.pydantic.dev/2.5/v/missing\n\nutils\\api_client.py:46: ValidationError"}, "steps": [{"name": "Get request to '/pet/findByStatus'", "status": "passed", "parameters": [{"name": "path", "value": "'/pet/findByStatus'"}, {"name": "params", "value": "{'status': 'sold'}"}], "start": 1704717211773, "stop": 1704717212518}, {"name": "Check status 200", "status": "passed", "start": 1704717212518, "stop": 1704717212518}, {"name": "Validate pet in response", "status": "broken", "statusDetails": {"message": "pydantic_core._pydantic_core.ValidationError: 1 validation error for Pet\nphotoUrls\n  Field required [type=missing, input_value={'id': 777, 'category': {...': [], 'status': 'sold'}, input_type=dict]\n    For further information visit https://errors.pydantic.dev/2.5/v/missing\n", "trace": "  File \"D:\\Pycharm_Projects\\api-testing-exam\\tests\\test_api.py\", line 174, in test_find_pet_200\n    assert api_client.validate_response(pet, Pet)\n  File \"D:\\Pycharm_Projects\\api-testing-exam\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"D:\\Pycharm_Projects\\api-testing-exam\\utils\\api_client.py\", line 46, in validate_response\n    return model.model_validate(result)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Pycharm_Projects\\api-testing-exam\\.venv\\Lib\\site-packages\\pydantic\\main.py\", line 503, in model_validate\n    return cls.__pydantic_validator__.validate_python(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "steps": [{"name": "Validate response data", "status": "broken", "statusDetails": {"message": "pydantic_core._pydantic_core.ValidationError: 1 validation error for Pet\nphotoUrls\n  Field required [type=missing, input_value={'id': 777, 'category': {...': [], 'status': 'sold'}, input_type=dict]\n    For further information visit https://errors.pydantic.dev/2.5/v/missing\n", "trace": "  File \"D:\\Pycharm_Projects\\api-testing-exam\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"D:\\Pycharm_Projects\\api-testing-exam\\utils\\api_client.py\", line 46, in validate_response\n    return model.model_validate(result)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Pycharm_Projects\\api-testing-exam\\.venv\\Lib\\site-packages\\pydantic\\main.py\", line 503, in model_validate\n    return cls.__pydantic_validator__.validate_python(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "parameters": [{"name": "result", "value": "{'id': 777, 'category': {'id': 888, 'name': 'This is my new category'}, 'name': 'This is my new pet', 'tags': [], 'status': 'sold'}"}, {"name": "model", "value": "<class 'models.pet.Pet'>"}], "start": 1704717212518, "stop": 1704717212518}], "start": 1704717212518, "stop": 1704717212518}], "attachments": [{"name": "stdout", "source": "a028236c-94ce-471f-9561-23eee2ef5d9f-attachment.txt", "type": "text/plain"}], "start": 1704717211773, "stop": 1704717212519, "uuid": "28f5f9fa-c119-4df6-886a-5b166d020619", "historyId": "d3c570e42e25cff890ef4e13c645562a", "testCaseId": "d3c570e42e25cff890ef4e13c645562a", "fullName": "tests.test_api.TestApi#test_find_pet_200", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api"}, {"name": "subSuite", "value": "TestApi"}, {"name": "host", "value": "DESKTOP-CPFF6BR"}, {"name": "thread", "value": "6492-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api"}]}